Resources:
  Efs:
    Type: AWS::EFS::FileSystem
    Properties: {}

  MountA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: Efs
      SecurityGroups:
        - Ref: EfsSg
      SubnetId:
        Ref: SubnetA

  MountB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: Efs
      SecurityGroups:
        - Ref: EfsSg
      SubnetId: 
        Ref: SubnetB

  EfsSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ${self:service}-efs
      GroupDescription: ${self:service}-efs
      SecurityGroupIngress:
        - FromPort: 2049
          ToPort: 2049
          IpProtocol: tcp
          SourceSecurityGroupId:
            Ref: Ec2Sg
      VpcId:
        Ref: Vpc
