Resources:
  Vpc: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.100.0.0/26
      EnableDnsSupport: true
      EnableDnsHostnames: true

  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select: 
          - 0
          - Fn::GetAZs:
              Ref: 'AWS::Region'
      CidrBlock:
        Fn::Select:
          - 0
          - Fn::Cidr: 
            - 10.100.0.0/26
            - 4
            - 4
      VpcId:
        Ref: Vpc  

  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: 
              Ref: 'AWS::Region'
      CidrBlock:
        Fn::Select: 
          - 1
          - Fn::Cidr: 
            - 10.100.0.0/26
            - 4
            - 4
      VpcId:
        Ref: Vpc

  SubnetARoute:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: RouteTable
      SubnetId:
        Ref: SubnetA

  SubnetBRoute:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: RouteTable
      SubnetId:
        Ref: SubnetB  

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: {}

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: Vpc

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: 
        Ref: Vpc    

  Route:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: 
        Ref: InternetGateway
      RouteTableId:
        Ref: RouteTable
